docker-compose-yaml: docker-compose.yml

# Inject the deployed Git SHA.
environment_variables:
  git_sha: 'true'

# Uncomment to login into container registries if using private images.
# container-registries:
#  dockerhub:
#    # Environment variables DOCKER_USER and DOCKER_PASS needs to be set via Lagoon CLI.
#    username: DOCKER_USER
#    password: DOCKER_PASS

tasks:
  post-rollout:
    - run:
        name: Show DrevOps variables.
        command: |
          [ "${DREVOPS_DEBUG-}" = "1" ] && env -0  | sort -z | tr '\0' '\n' | grep ^DREVOPS_ || true
        service: cli
        shell: bash

    - run:
        name: Notify about pre-deployment.
        command: |
          if [ -n "$LAGOON_PR_NUMBER" ]; then export DREVOPS_NOTIFY_REF=$LAGOON_PR_NUMBER;export DREVOPS_NOTIFY_SHA=${LAGOON_PR_HEAD_SHA#origin/};export DREVOPS_NOTIFY_BRANCH=$LAGOON_PR_HEAD_BRANCH;else export DREVOPS_NOTIFY_REF=$LAGOON_GIT_BRANCH;export DREVOPS_NOTIFY_SHA=$LAGOON_GIT_SHA;export DREVOPS_NOTIFY_BRANCH=$LAGOON_GIT_BRANCH;fi
          DREVOPS_NOTIFY_PROJECT=$LAGOON_PROJECT \
          DREVOPS_NOTIFY_ENVIRONMENT_URL=$LAGOON_ROUTE \
          DREVOPS_NOTIFY_EVENT=pre_deployment ./scripts/drevops/notify.sh || true
        service: cli
        shell: bash

    - run:
        name: Backup DB before deployment in production
        command: |
          if [ "$LAGOON_ENVIRONMENT_TYPE" = "production" ] || [ "$LAGOON_GIT_BRANCH" = "${DREVOPS_LAGOON_PRODUCTION_BRANCH:-main}" ]; then
            echo "==> Running in PRODUCTION environment."
            DREVOPS_DB_DIR=/app/web/sites/default/files/private/pre_deployment_backups ./scripts/drevops/export-db-file.sh
          fi
        service: cli

    - run:
        name: Download database in non-production environments
        command: |
          if [ "$LAGOON_ENVIRONMENT_TYPE" != "production" ] && [ "$LAGOON_GIT_BRANCH" != "${DREVOPS_LAGOON_PRODUCTION_BRANCH:-main}" ]; then
            # No need to load SSH file to access production DB as Lagoon has SSH agent keys.
            export DREVOPS_DB_DOWNLOAD_SSH_KEY_FILE=false
            export DREVOPS_DB_DIR=/tmp/data
            rm -Rf $DREVOPS_DB_DIR || true
            ./scripts/drevops/download-db.sh
          fi
        service: cli

    - run:
        name: Provision site
        command: |

          if [ "$LAGOON_ENVIRONMENT_TYPE" = "production" ] || [ "$LAGOON_GIT_BRANCH" = "${DREVOPS_LAGOON_PRODUCTION_BRANCH:-main}" ]; then
            echo "==> Running in PRODUCTION environment."
            # Never overwrite existing DB when production site already exists.
            export DREVOPS_PROVISION_OVERRIDE_DB=0
            # Never unblock admin user in production.
            export DRUPAL_UNBLOCK_ADMIN=0
            # Never sanitize DB in production.
            export DREVOPS_PROVISION_SANITIZE_DB_SKIP=1
          fi

          export DREVOPS_DB_DIR=/tmp/data
          ./scripts/drevops/provision.sh
          ./.docker/scripts/deploy.sh
        service: cli
        shell: bash

    - run:
        name: Send deployment notifications
        command: |
          if [ -n "$LAGOON_PR_NUMBER" ]; then export DREVOPS_NOTIFY_REF=$LAGOON_PR_NUMBER; export DREVOPS_NOTIFY_SHA=${LAGOON_PR_HEAD_SHA#origin/}; export DREVOPS_NOTIFY_BRANCH=$LAGOON_PR_HEAD_BRANCH; else export DREVOPS_NOTIFY_REF=$LAGOON_GIT_BRANCH; export DREVOPS_NOTIFY_SHA=$LAGOON_GIT_SHA; export DREVOPS_NOTIFY_BRANCH=$LAGOON_GIT_BRANCH; fi
          DREVOPS_NOTIFY_EVENT=post_deployment \
          DREVOPS_NOTIFY_PROJECT=$LAGOON_PROJECT \
          DREVOPS_NOTIFY_ENVIRONMENT_URL=$LAGOON_ROUTE \
          ./scripts/drevops/notify.sh
        service: cli
        shell: bash
environments:
  # Branch name that represents production environment.
  production:
    cronjobs:
      - name: drush cron
        schedule: '*/15 * * * *'
        command: drush cron --root=/app
        service: cli
    # Uncomment to enable installing a custom SSL certificate.
    # By default, Lagoon installs Let's Encrypt certificates for all environments.
    autogenerateRoutes: false
    routes:
      - nginx-php:
          - "scaffold-testig.lagoon.salsa.hosting":
              tls-acme: 'false'
              insecure: Redirect
              hsts: max-age=31536000
    monitoring_urls:
      - scaffold-testig.lagoon.salsa.hosting
  # Branch name that represents development environment.
  develop:
    cronjobs:
      - name: drush cron
        schedule: '*/15 * * * *'
        command: drush cron --root=/app
        service: cli
routes:
  insecure: Redirect
